Parse config and replicate Myrra engine
lambdaclass/lambda_game_engine pull request #1
Opened 2023-09-12 20:43 UTC by AminArria

- Functionality to parse a config file based on how the new config would look. An important thing to notice is how the config has several strings that are named references to others (e.g. skill name) and that is why we do the later lookup on them
- Copy of current engine in "Curse of Myrra", this will help with the extraction from it as we can directly remove it in the project and do the refactors in this library

2023-09-13 17:00 UTC, ncontinanza requested changes

2023-09-13 17:00 UTC, ncontinanza commented on native/lambda_game_engine/src/myra_engine/game.rs
> +        position = generate_new_position(&mut tried_positions, self.board.width, self.board.height);
```suggestion
        let position = generate_new_position(&mut tried_positions, self.board.width, self.board.height);
```

2023-09-13 17:00 UTC, ncontinanza commented on native/lambda_game_engine/src/myra_engine/game.rs
> +/// Example: If the arguments are Direction::RIGHT, (0, 0) and 2, returns (0, 2).
```suggestion
/// Example: If the arguments are `Direction::RIGHT`, (0, 0) and 2, returns (0, 2).
```

2023-09-13 17:00 UTC, ncontinanza commented on native/lambda_game_engine/src/myra_engine/player.rs
> +}
```suggestion
pub enum Status {
    Alive,
    Dead,
    Disconnected,
}
```

2023-09-13 17:00 UTC, ncontinanza commented on native/lambda_game_engine/src/myra_engine/player.rs
> +}
If you accept this suggestion, please remember to change it everywhere these values are used.

2023-09-13 17:00 UTC, ncontinanza commented on native/lambda_game_engine/src/myra_engine/player.rs
> +}
```suggestion
pub enum PlayerAction {
    Nothing,
    Attacking,
    AttackingAOE,
    StartingSkill1,
    StartingSkill2,
    StartingSkill3,
    StartingSkill4,
    ExecutingSkill1,
    ExecutingSkill2,
    ExecutingSkill3,
    ExecutingSkill4,
    Moving,
}
```

2023-09-13 17:00 UTC, ncontinanza commented on native/lambda_game_engine/src/myra_engine/player.rs
> +        return random <= chance;
```suggestion
        random <= chance
```

2023-09-15 13:32 UTC, AminArria commented on native/lambda_game_engine/src/myra_engine/game.rs
> +        Ok(())
We could remove it, honestly don't have a strong opinion about it and don't know about conventions in Rust. Let's look into this

2023-09-15 13:37 UTC, AminArria commented on native/lambda_game_engine/src/character.rs
> +                    skill_5: skill_5.clone(),
Yes, but those variables are references (`&SkillConfig`) and needed that copy of the skill to have it in the character

2023-09-15 13:50 UTC, AminArria commented on native/lambda_game_engine/src/myra_engine/game.rs
> +    RIGHT,
Changing this enums is not trivial because the Myrra server and the client expect them like that

2023-09-15 13:51 UTC, AminArria commented on native/lambda_game_engine/src/myra_engine.rs
Damn, yes, need to fix it

2023-09-15 14:11 UTC, ncontinanza commented on native/lambda_game_engine/src/myra_engine/game.rs
> +        Ok(())
About that: https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_wraps

2023-09-15 18:01 UTC, AminArria commented on native/lambda_game_engine/src/myra_engine.rs
Fixed in [1c79e39](https://github.com/lambdaclass/lambda_game_engine/pull/1/commits/1c79e3926f19f5d1dba6414b75ba45247652e720)

2023-09-15 18:02 UTC, AminArria commented on native/lambda_game_engine/src/character.rs
> +                    );
Done in [baccf9c](https://github.com/lambdaclass/lambda_game_engine/pull/1/commits/baccf9cf4adf70a9fdf603c19893353ed684ada6)

2023-09-15 18:15 UTC, ncontinanza approved these changes
LGTM! 🚀

2023-09-15 18:16 UTC, merged